"""Seed data for financial instruments in Mexico.

Populates the instruments table with initial data so the optimizer
and Fina agent have instruments to work with before scrapers run.
Scrapers will update rates periodically.
"""

from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from backend.models.instruments import Instrument

INSTRUMENTS_SEED = [
    # CETES
    {
        "name": "CETES 28 días",
        "institution": "Gobierno Federal (cetesdirecto)",
        "instrument_type": "cetes",
        "annual_rate": 10.5,
        "min_investment": 100,
        "max_investment": None,
        "term": "28",
        "term_days": 28,
        "risk_level": "low",
        "liquidity_tier": "28-day",
        "requires_purchase": False,
        "conditions": "Deuda gubernamental. Plazo fijo 28 días.",
    },
    {
        "name": "CETES 91 días",
        "institution": "Gobierno Federal (cetesdirecto)",
        "instrument_type": "cetes",
        "annual_rate": 10.3,
        "min_investment": 100,
        "max_investment": None,
        "term": "91",
        "term_days": 91,
        "risk_level": "low",
        "liquidity_tier": "custom",
        "requires_purchase": False,
        "conditions": "Deuda gubernamental. Plazo fijo 91 días.",
    },
    {
        "name": "CETES 182 días",
        "institution": "Gobierno Federal (cetesdirecto)",
        "instrument_type": "cetes",
        "annual_rate": 10.1,
        "min_investment": 100,
        "max_investment": None,
        "term": "182",
        "term_days": 182,
        "risk_level": "low",
        "liquidity_tier": "custom",
        "requires_purchase": False,
        "conditions": "Deuda gubernamental. Plazo fijo 182 días.",
    },
    {
        "name": "CETES 364 días",
        "institution": "Gobierno Federal (cetesdirecto)",
        "instrument_type": "cetes",
        "annual_rate": 9.8,
        "min_investment": 100,
        "max_investment": None,
        "term": "364",
        "term_days": 364,
        "risk_level": "low",
        "liquidity_tier": "custom",
        "requires_purchase": False,
        "conditions": "Deuda gubernamental. Plazo fijo 364 días.",
    },
    # Nu México
    {
        "name": "Nu Cuenta",
        "institution": "Nu México",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 13.0,
        "min_investment": 0.01,
        "max_investment": 25000,
        "term": "liquid",
        "term_days": None,
        "risk_level": "low",
        "liquidity_tier": "immediate",
        "requires_purchase": True,
        "conditions": "Cajita Turbo: 13% anual. Requiere una compra al mes.",
    },
    {
        "name": "Nu Cajitas",
        "institution": "Nu México",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 6.5,
        "min_investment": 0.01,
        "max_investment": None,
        "term": "liquid",
        "term_days": None,
        "risk_level": "low",
        "liquidity_tier": "immediate",
        "requires_purchase": False,
        "conditions": "Cajitas Nu: disponible 24/7, sin congelar.",
    },
    {
        "name": "Nu Congelado 7 días",
        "institution": "Nu México",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 6.55,
        "min_investment": 50,
        "max_investment": None,
        "term": "7",
        "term_days": 7,
        "risk_level": "low",
        "liquidity_tier": "1-day",
        "requires_purchase": False,
        "conditions": "Ahorro congelado 7 días.",
    },
    {
        "name": "Nu Congelado 28 días",
        "institution": "Nu México",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 6.6,
        "min_investment": 50,
        "max_investment": None,
        "term": "28",
        "term_days": 28,
        "risk_level": "low",
        "liquidity_tier": "28-day",
        "requires_purchase": False,
        "conditions": "Ahorro congelado 28 días.",
    },
    {
        "name": "Nu Congelado 90 días",
        "institution": "Nu México",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 6.7,
        "min_investment": 50,
        "max_investment": None,
        "term": "90",
        "term_days": 90,
        "risk_level": "low",
        "liquidity_tier": "custom",
        "requires_purchase": False,
        "conditions": "Ahorro congelado 90 días.",
    },
    {
        "name": "Nu Congelado 180 días",
        "institution": "Nu México",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 6.8,
        "min_investment": 50,
        "max_investment": None,
        "term": "180",
        "term_days": 180,
        "risk_level": "low",
        "liquidity_tier": "custom",
        "requires_purchase": False,
        "conditions": "Ahorro congelado 180 días.",
    },
    # Didi
    {
        "name": "Didi Cuenta",
        "institution": "Didi (99 Pay)",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 15.0,
        "min_investment": 0,
        "max_investment": 10000,
        "term": "liquid",
        "term_days": None,
        "risk_level": "low",
        "liquidity_tier": "immediate",
        "requires_purchase": False,
        "conditions": "15% GAT sobre primeros $10,000. Excedente 7.5%.",
    },
    # Mercado Pago
    {
        "name": "Mercado Pago",
        "institution": "Mercado Libre",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 13.0,
        "min_investment": 0,
        "max_investment": None,
        "term": "liquid",
        "term_days": None,
        "risk_level": "low",
        "liquidity_tier": "immediate",
        "requires_purchase": False,
        "conditions": "Rendimiento diario sin límite. Disponibilidad inmediata.",
    },
    # Ualá
    {
        "name": "Ualá Cuenta",
        "institution": "Ualá",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 6.75,
        "min_investment": 100,
        "max_investment": 30000,
        "term": "liquid",
        "term_days": None,
        "risk_level": "low",
        "liquidity_tier": "immediate",
        "requires_purchase": False,
        "conditions": "Tasa base 6.75% anual. Hasta $30,000.",
    },
    {
        "name": "Ualá Cuenta Plus",
        "institution": "Ualá",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 12.0,
        "min_investment": 100,
        "max_investment": 30000,
        "term": "liquid",
        "term_days": None,
        "risk_level": "low",
        "liquidity_tier": "immediate",
        "requires_purchase": True,
        "conditions": "Requiere consumo mínimo de $3,000 al mes.",
    },
    {
        "name": "Ualá Cuenta Plus Alta",
        "institution": "Ualá",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 15.0,
        "min_investment": 100,
        "max_investment": 30000,
        "term": "liquid",
        "term_days": None,
        "risk_level": "low",
        "liquidity_tier": "immediate",
        "requires_purchase": True,
        "conditions": "Requiere consumo mínimo de $6,000 al mes.",
    },
    {
        "name": "Ualá Reserva a Plazo",
        "institution": "Ualá",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 7.4,
        "min_investment": 10,
        "max_investment": None,
        "term": "365",
        "term_days": 365,
        "risk_level": "low",
        "liquidity_tier": "custom",
        "requires_purchase": False,
        "conditions": "Plazo fijo 365 días.",
    },
    # Klar
    {
        "name": "Klar Cuenta",
        "institution": "Klar",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 3.0,
        "min_investment": 100,
        "max_investment": None,
        "term": "liquid",
        "term_days": None,
        "risk_level": "low",
        "liquidity_tier": "immediate",
        "requires_purchase": False,
        "conditions": "Rendimiento diario 3% anual.",
    },
    {
        "name": "Klar Inversión",
        "institution": "Klar",
        "instrument_type": "inversion_fija",
        "annual_rate": 8.5,
        "min_investment": 100,
        "max_investment": None,
        "term": "365",
        "term_days": 365,
        "risk_level": "low",
        "liquidity_tier": "custom",
        "requires_purchase": True,
        "conditions": "Requiere membresía Klar Plus/Platino. Inversión fija 365 días.",
    },
    # Finsus
    {
        "name": "Finsus Tasa Especial",
        "institution": "Finsus",
        "instrument_type": "inversion_fija",
        "annual_rate": 11.5,
        "min_investment": 100,
        "max_investment": None,
        "term": "120",
        "term_days": 120,
        "risk_level": "low",
        "liquidity_tier": "custom",
        "requires_purchase": False,
        "conditions": "Plazo fijo 120 días. Tasa especial por tiempo limitado.",
    },
    {
        "name": "Finsus Inversión",
        "institution": "Finsus",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 9.09,
        "min_investment": 100,
        "max_investment": None,
        "term": "liquid",
        "term_days": None,
        "risk_level": "low",
        "liquidity_tier": "immediate",
        "requires_purchase": False,
        "conditions": "Inversiones flexibles hasta 9.09% anual.",
    },
    # Stori
    {
        "name": "Stori Apartados",
        "institution": "Stori",
        "instrument_type": "cuenta_ahorro",
        "annual_rate": 7.0,
        "min_investment": 10,
        "max_investment": None,
        "term": "liquid",
        "term_days": None,
        "risk_level": "low",
        "liquidity_tier": "immediate",
        "requires_purchase": False,
        "conditions": "Crecimiento diario, dinero disponible.",
    },
    {
        "name": "Stori Inversión+ 30 días",
        "institution": "Stori",
        "instrument_type": "inversion_fija",
        "annual_rate": 7.05,
        "min_investment": 10,
        "max_investment": None,
        "term": "30",
        "term_days": 30,
        "risk_level": "low",
        "liquidity_tier": "28-day",
        "requires_purchase": False,
        "conditions": "Plazo fijo 30 días.",
    },
    {
        "name": "Stori Inversión+ 90 días",
        "institution": "Stori",
        "instrument_type": "inversion_fija",
        "annual_rate": 9.0,
        "min_investment": 10,
        "max_investment": None,
        "term": "90",
        "term_days": 90,
        "risk_level": "low",
        "liquidity_tier": "custom",
        "requires_purchase": False,
        "conditions": "Plazo fijo 90 días.",
    },
    {
        "name": "Stori Inversión+ 180 días",
        "institution": "Stori",
        "instrument_type": "inversion_fija",
        "annual_rate": 8.25,
        "min_investment": 10,
        "max_investment": None,
        "term": "180",
        "term_days": 180,
        "risk_level": "low",
        "liquidity_tier": "custom",
        "requires_purchase": False,
        "conditions": "Plazo fijo 180 días.",
    },
]


async def seed_instruments(db: AsyncSession) -> None:
    """Insert seed instruments if the table is empty."""
    result = await db.execute(select(Instrument).limit(1))
    existing = result.scalar_one_or_none()

    if existing:
        return  # Already has data

    now = datetime.now(timezone.utc)
    for data in INSTRUMENTS_SEED:
        instrument = Instrument(
            name=data["name"],
            institution=data["institution"],
            instrument_type=data["instrument_type"],
            annual_rate=data["annual_rate"],
            min_investment=data["min_investment"],
            max_investment=data.get("max_investment"),
            term=data["term"],
            term_days=data.get("term_days"),
            risk_level=data["risk_level"],
            liquidity_tier=data["liquidity_tier"],
            requires_purchase=data.get("requires_purchase", False),
            conditions=data.get("conditions"),
            last_fetch_status="success",
            last_fetched_at=now,
        )
        db.add(instrument)

    await db.commit()
    print(f"[Seed] Inserted {len(INSTRUMENTS_SEED)} instruments.")
