"""initial_schema_all_15_tables

Revision ID: 9fb01fd433c1
Revises: 
Create Date: 2026-07-21 19:54:48.589920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb01fd433c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('lesson_count', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instruments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('annual_rate', sa.Numeric(precision=8, scale=4), nullable=False, comment='Annual rate percentage'),
    sa.Column('min_investment', sa.Numeric(precision=18, scale=2), nullable=False, comment='Minimum investment amount'),
    sa.Column('max_investment', sa.Numeric(precision=18, scale=2), nullable=True, comment='Maximum investment amount (nullable)'),
    sa.Column('term', sa.String(length=50), nullable=False, comment="Term in days or 'liquid'"),
    sa.Column('risk_level', sa.String(length=10), nullable=False, comment='low, medium, or high'),
    sa.Column('liquidity_tier', sa.String(length=20), nullable=False, comment='immediate, 1-day, 28-day, or custom'),
    sa.Column('tiered_rates', sa.JSON(), nullable=True, comment='Array of {min_amount, max_amount, rate} objects'),
    sa.Column('last_fetch_status', sa.String(length=20), nullable=False, comment='success or error'),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(length=128), nullable=False, comment='Firebase UID'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('afore',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('balance_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted balance'),
    sa.Column('last_update_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_afore_user_id', 'afore', ['user_id'], unique=False)
    op.create_table('ahorro',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('amount_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted monetary amount'),
    sa.Column('account_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ahorro_user_id', 'ahorro', ['user_id'], unique=False)
    op.create_table('aportaciones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('amount_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted contribution amount'),
    sa.Column('frequency', sa.String(length=20), nullable=False, comment='weekly, biweekly, or monthly'),
    sa.Column('target_name', sa.String(length=100), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_aportaciones_user_id', 'aportaciones', ['user_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='Protected system categories'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_categories_user_id', 'categories', ['user_id'], unique=False)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('current_state', sa.String(length=50), nullable=False, comment='FSM state name'),
    sa.Column('collected_params', sa.JSON(), nullable=True, comment='Collected optimizer parameters'),
    sa.Column('messages', sa.JSON(), nullable=False, comment='Conversation message history'),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_sessions_user_id', 'conversation_sessions', ['user_id'], unique=False)
    op.create_table('creditos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('balance_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted balance'),
    sa.Column('limit_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted credit limit'),
    sa.Column('min_payment_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted minimum payment'),
    sa.Column('card_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_creditos_user_id', 'creditos', ['user_id'], unique=False)
    op.create_table('deudas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('creditor_name', sa.String(length=100), nullable=False),
    sa.Column('total_amount_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted total debt amount'),
    sa.Column('monthly_payment_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted monthly payment'),
    sa.Column('interest_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Annual interest rate 0.00-100.00'),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deudas_user_id', 'deudas', ['user_id'], unique=False)
    op.create_table('gbm_portfolio',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('shares', sa.Numeric(precision=18, scale=6), nullable=False, comment='Number of shares, precision 6'),
    sa.Column('avg_cost_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted average cost per share'),
    sa.Column('market_value_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted current market value'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gbm_portfolio_user_id', 'gbm_portfolio', ['user_id'], unique=False)
    op.create_table('lessons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('update_tracker',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('module_name', sa.String(length=50), nullable=False, comment='Module identifier (ahorro, creditos, etc.)'),
    sa.Column('last_updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_update_tracker_user_id', 'update_tracker', ['user_id'], unique=False)
    op.create_table('gastos_ingresos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False, comment='income or expense'),
    sa.Column('amount_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted monetary amount'),
    sa.Column('description_encrypted', sa.Text(), nullable=False, comment='Fernet-encrypted description'),
    sa.Column('category_id', sa.String(length=36), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gastos_ingresos_user_id', 'gastos_ingresos', ['user_id'], unique=False)
    op.create_table('lesson_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('lesson_id', sa.String(length=36), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['lesson_id'], ['lessons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_lesson_progress_user_id', 'lesson_progress', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_lesson_progress_user_id', table_name='lesson_progress')
    op.drop_table('lesson_progress')
    op.drop_index('ix_gastos_ingresos_user_id', table_name='gastos_ingresos')
    op.drop_table('gastos_ingresos')
    op.drop_index('ix_update_tracker_user_id', table_name='update_tracker')
    op.drop_table('update_tracker')
    op.drop_table('lessons')
    op.drop_index('ix_gbm_portfolio_user_id', table_name='gbm_portfolio')
    op.drop_table('gbm_portfolio')
    op.drop_index('ix_deudas_user_id', table_name='deudas')
    op.drop_table('deudas')
    op.drop_index('ix_creditos_user_id', table_name='creditos')
    op.drop_table('creditos')
    op.drop_index('ix_conversation_sessions_user_id', table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index('ix_categories_user_id', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_aportaciones_user_id', table_name='aportaciones')
    op.drop_table('aportaciones')
    op.drop_index('ix_ahorro_user_id', table_name='ahorro')
    op.drop_table('ahorro')
    op.drop_index('ix_afore_user_id', table_name='afore')
    op.drop_table('afore')
    op.drop_table('users')
    op.drop_table('instruments')
    op.drop_table('courses')
    # ### end Alembic commands ###
